version: "3.9"
services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "maindb"
      POSTGRES_USER: "maindb"
      POSTGRES_PASSWORD: "maindb"
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data
